Repository Rurusetto/rurusetto, pull requests merged in 2021-05, with the labels that each got.

#6 Add more ruleset page
  content/.DS_Store
  content/pages/status/index.md
  content/posts/.DS_Store
  content/posts/bosu/bosu-logo.png
  content/posts/bosu/index.md
  content/posts/bosu/mod-icon/autoplay-mod.png
  content/posts/bosu/mod-icon/double-time-mod.png
  content/posts/bosu/mod-icon/easy-mod.png
  content/posts/bosu/mod-icon/half-time-mod.png
  content/posts/bosu/mod-icon/hidden-mod.png
  content/posts/bosu/mod-icon/no-fail-mod.png
  content/posts/bosu/mod-icon/sudden-death-mod.png
  content/posts/bosu/mod-icon/wind-up-mod.png
  content/posts/cytosu/index.md
  content/posts/hitokori/index.md
  content/posts/mvis/index.md
  content/posts/mvis/mod-icon/double-time-mod.png
  content/posts/mvis/mod-icon/half-time-mod.png
  content/posts/mvis/mvis-logo.png
  content/posts/rush/index.md
  content/posts/swing/index.md
  content/posts/swing/mod-icon/alternate-mod.png
  content/posts/swing/mod-icon/autoplay-mod.png
  content/posts/swing/mod-icon/difficulty-adjust-mod.png
  content/posts/swing/mod-icon/double-time-mod.png
  content/posts/swing/mod-icon/easy-mod.png
  content/posts/swing/mod-icon/half-time-mod.png
  content/posts/swing/mod-icon/no-fail-mod.png
  content/posts/swing/mod-icon/no-sliders-mod.png
  content/posts/swing/mod-icon/sudden-death-mod.png
  content/posts/swing/mod-icon/wind-up-mod.png
  content/posts/swing/swing-logo.png
Labels: new-ruleset

#13 Update mvis tag
  content/pages/status/index.md
  content/posts/mvis/index.md
Labels: size/XS, update

#12 First patch of dark mode and other code structure improvement
  .gitignore
  config.toml
  content/pages/status/index.md
  resources/_gen/assets/scss/sass/main.scss_c25f88f67e8e33f20619c76cbf49f33c.content
  static/temporary-logo.svg
  themes/hugo-cards/assets/sass/_bootstrap-readable.scss
  themes/hugo-cards/layouts/partials/footer.html
  themes/hugo-cards/layouts/partials/head.html
  themes/hugo-cards/layouts/partials/header.html
  themes/hugo-cards/layouts/partials/seo.html
  themes/hugo-cards/layouts/partials/sidebar.html
  themes/hugo-cards/layouts/shortcodes/picture.html
  themes/hugo-cards/static/css/custom.css
Labels: enhancement, priority: 2, size/L

#14 Fixed Mistakes™
  content/posts/hishigata/index.md
Labels: size/S

#16 Add dev warning and change analystic ID
  config.toml
  themes/hugo-cards/layouts/_default/list.html
  themes/hugo-cards/static/css/custom.css
Labels: size/S

#17 Add readme detail and add a new page
  README.md
  config.toml
  content/pages/install/img/open-osu-folder.png
  content/pages/install/img/rulesets-complete.png
  content/pages/install/img/sentakki-release-download.png
  content/pages/install/img/status-download.png
  content/pages/install/index.md
  content/pages/status/index.md
  content/posts/cytosu/cytosu-logo.png
  themes/hugo-cards/layouts/_default/list.html
  themes/hugo-cards/layouts/partials/header.html
  themes/hugo-cards/static/css/custom.css
Labels: can-build, size/M

#18 Change analystic ID, update cytosu and add soyokaze!
  README.md
  config.toml
  content/pages/status/index.md
  content/posts/.DS_Store
  content/posts/cytosu/index.md
  content/posts/cytosu/mod-icon/double-time-mod.png
  content/posts/cytosu/mod-icon/half-time-mod.png
  content/posts/cytosu/mod-icon/relax-mod.png
  content/posts/hitokori/index.md
  content/posts/mvis/index.md
  content/posts/soyokaze/index.md
  content/posts/soyokaze/mod-icon/autoplay-mod.png
  content/posts/soyokaze/mod-icon/difficulty-adjust-mod.png
  content/posts/soyokaze/mod-icon/double-time-mod.png
  content/posts/soyokaze/mod-icon/easy-mod.png
  content/posts/soyokaze/mod-icon/half-time-mod.png
  content/posts/soyokaze/mod-icon/hard-rock-mod.png
  content/posts/soyokaze/mod-icon/no-fail-mod.png
  content/posts/soyokaze/mod-icon/random-mod.png
  content/posts/soyokaze/mod-icon/sudden-death-mod.png
  content/posts/soyokaze/mod-icon/wind-up-mod.png
  content/posts/soyokaze/soyokaze-logo.png
  themes/hugo-cards/static/css/custom.css
Labels: can-build, size/L

#22 Add code of conduct
  README.md
  code_of_conduct.md
  content/posts/touhosu/index.md
Labels: size/L

#23 Update wiki and readme
  README.md
  content/posts/hishigata/index.md
  content/posts/hitokori/index.md
  content/posts/mvis/index.md
  content/posts/rush/index.md
  content/posts/tau/index.md
  content/posts/touhosu/index.md
  content/posts/yoso/index.md
Labels: size/M

#27 Update osu!diva and mvis wiki
  content/posts/mvis/index.md
  content/posts/osu-diva/index.md
  content/posts/osu-diva/mod-icon/no-doubles-mod.png
  content/posts/osu-diva/mod-icon/one-button-mod.png
Labels: area:wiki
