Repository Rurusetto/rurusetto, pull requests merged in 2021-10, with the labels that each got.

#84 Update readme and write a contributor guideline
  CONTRIBUTING.md
  README.md
  code_of_conduct.md
Labels: size/L, type:documentation

#90 Initialize the status page
  rurusetto/wiki/function.py
  rurusetto/wiki/static/img/status-cover-light.jpg
  rurusetto/wiki/static/img/status-cover-night.jpg
  rurusetto/wiki/templates/wiki/base.html
  rurusetto/wiki/templates/wiki/edit_ruleset_wiki.html
  rurusetto/wiki/templates/wiki/status.html
  rurusetto/wiki/templates/wiki/subpage.html
  rurusetto/wiki/urls.py
  rurusetto/wiki/views.py
Labels: size/L, type:new-function, area:status

#94 Fix some grammatical errors and typos in README.MD and CONTRIBUTING.MD
  CONTRIBUTING.md
  README.md
Labels: size/S, type:documentation

#93 Fixed grammar on Website
  rurusetto/templates/404.html
  rurusetto/users/templates/account/login.html
  rurusetto/users/templates/account/signup.html
  rurusetto/users/templates/socialaccount/connections.html
  rurusetto/users/templates/socialaccount/login_cancelled.html
  rurusetto/users/templates/users/delete_account.html
  rurusetto/users/templates/users/login.html
  rurusetto/users/templates/users/logout.html
  rurusetto/users/templates/users/register.html
  rurusetto/users/templates/users/settings.html
  rurusetto/users/views.py
  rurusetto/wiki/templates/wiki/create_ruleset.html
  rurusetto/wiki/templates/wiki/edit_ruleset_wiki.html
  rurusetto/wiki/templates/wiki/home.html
  rurusetto/wiki/views.py
Labels: size/L, type:code-quality

#99 Initial setup of the worker
  rurusetto/wiki/action.py
  rurusetto/wiki/admin.py
  rurusetto/wiki/migrations/0040_action.py
  rurusetto/wiki/migrations/0041_auto_20211003_1906.py
  rurusetto/wiki/migrations/0042_alter_action_time_finish.py
  rurusetto/wiki/models.py
  rurusetto/wiki/static/img/maintainer-cover-light.jpg
  rurusetto/wiki/static/img/maintainer-cover-night.png
  rurusetto/wiki/static/img/maintainer-cover-night2.png
  rurusetto/wiki/templates/wiki/base.html
  rurusetto/wiki/templates/wiki/maintainer.html
  rurusetto/wiki/urls.py
  rurusetto/wiki/views.py
Labels: size/L, area:database, type:new-function

#104 Finish the status page
  requirements.txt
  rurusetto/rurusetto/settings.py
  rurusetto/users/static/css/index.css
  rurusetto/wiki/action.py
  rurusetto/wiki/admin.py
  rurusetto/wiki/apps.py
  rurusetto/wiki/function.py
  rurusetto/wiki/migrations/0043_merge_20211005_1701.py
  rurusetto/wiki/migrations/0044_rulesetstatus.py
  rurusetto/wiki/migrations/0045_alter_rulesetstatus_latest_update.py
  rurusetto/wiki/models.py
  rurusetto/wiki/signals.py
  rurusetto/wiki/templates/wiki/maintainer.html
  rurusetto/wiki/templates/wiki/status.html
  rurusetto/wiki/urls.py
  rurusetto/wiki/views.py
Labels: size/L, type:new-function, area:backend, area:status

#106 Adjust beatmap card style
  rurusetto/users/static/css/index.css
  rurusetto/wiki/action.py
  rurusetto/wiki/migrations/0046_auto_20211006_0457.py
  rurusetto/wiki/models.py
  rurusetto/wiki/templates/wiki/snippets/beatmap_approval_card.html
  rurusetto/wiki/templates/wiki/snippets/beatmap_card.html
  rurusetto/wiki/templates/wiki/status.html
  rurusetto/wiki/templatetags/convert_file_size.py
  rurusetto/wiki/views.py
Labels: size/L

#107 Finalize the beatmap card styling
  rurusetto/users/static/css/index.css
  rurusetto/wiki/templates/wiki/maintainer.html
  rurusetto/wiki/templates/wiki/snippets/beatmap_approval_card.html
  rurusetto/wiki/templates/wiki/snippets/beatmap_card.html
Labels: size/M, area:recommend-beatmap, type:ui-ux, area:action
