Repository Rurusetto/rurusetto, pull requests merged in 2021-06, with the labels that each got.

#28 Add Sandbox to wiki
  content/pages/status/index.md
  content/posts/rush/index.md
  content/posts/rush/mod-icon/flashlight-mod.png
  content/posts/rush/mod-icon/sudden-death-mod.png
  content/posts/rush/mod-icon/wind-up-mod.png
  content/posts/sandbox/index.md
  content/posts/sandbox/sandbox-logo.png
  content/posts/yoso/index.md
Labels: area:wiki

#29 Update Sandbox and solosu wiki
  content/posts/sandbox/index.md
  content/posts/solosu/index.md
Labels: area:wiki, size/S

#33 Fix EVAST's Discord server link
  content/posts/bosu/index.md
  content/posts/sandbox/index.md
  content/posts/swing/index.md
  content/posts/touhosu/index.md
  removed/mvis/index.md
Labels: area:wiki, can-build, size/S

#34 Update soyokaze's new mod
  content/posts/soyokaze/index.md
  content/posts/soyokaze/mod-icon/holds-mod.png
Labels: area:wiki, can-build

#35 Update tau's new link.
  content/pages/status/index.md
  content/posts/tau/index.md
Labels: area:wiki, size/S
